# fly.toml app configuration file generated for easyshop on 2024-01-03T11:03:03-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "easyshop"
primary_region = "scl"


[env]
  SHOPIFY_API_KEY = "9ca203d7f7ae981cbeb1969837fc4df0"
  SCOPES = "write_products,write_publications,read_publications"
  PORT = "8081"
  SHOPIFY_APP_URL = "https://easyshop.fly.dev/"  



[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[services.cors]]
  allow_origin = "*"
  allow_headers = "Authorization"
