# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "easyshop"
client_id = "9ca203d7f7ae981cbeb1969837fc4df0"
application_url = "https://cooking-participants-organizations-contractor.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_publications,read_publications"

[auth]
redirect_urls = [
  "https://cooking-participants-organizations-contractor.trycloudflare.com/auth/callback",
  "https://cooking-participants-organizations-contractor.trycloudflare.com/auth/shopify/callback",
  "https://cooking-participants-organizations-contractor.trycloudflare.com/api/auth/callback",
  "https://cooking-participants-organizations-contractor.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2024-01"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://easyecommercelaravel-production.up.railway.app/api/shopify/webhooks/customer_redact"
  customer_data_request_url = "https://easyecommercelaravel-production.up.railway.app/api/shopify/webhooks/   
  customer_data_request"
  shop_deletion_url = "https://easyecommercelaravel-production.up.railway.app/api/shopify/webhooks/shop_redact"
[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-3ff52034.myshopify.com"
