# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "easyshop"
client_id = "9ca203d7f7ae981cbeb1969837fc4df0"
application_url = "https://easyshop-production.up.railway.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_publications,read_publications"

[auth]
redirect_urls = ["https://easyecommercelaravel-production.up.railway.app/api/auth/callback"]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-3ff52034.myshopify.com"
